---
# deploy-k8s-cluster.yml - Control from Raspberry Pi
- name: Complete K8s cluster deployment - VMs + Kubernetes
  hosts: localhost
  gather_facts: yes
  vars:
    vm_specs:
      k8s-control:
        memory: 4096
        vcpus: 2
        disk: 30
        role: control
      k8s-worker1:
        memory: 4096
        vcpus: 2
        disk: 20
        role: worker
      k8s-worker2:
        memory: 4096
        vcpus: 2
        disk: 20
        role: worker
    
    # SSH configuration
    ssh_user: ansible
    ssh_retries: 60  # 60 retries with 10 second delay = 10 minutes
    ssh_delay: 10
    ssh_timeout: 600  # 10 minutes timeout for SSH operations
    
    # Your Raspberry Pi SSH public key - you'll need to paste yours here
    ssh_public_key_content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA/EjjlcKFIT5KO3lCefJLxI61ZYL2oQ6Zlr665Y2CKn michaelpsachs@gmail.com"

    
    # Network configuration
    network_name: default
    base_image: "/var/lib/libvirt/images/ubuntu-22.04-server-cloudimg-amd64.img"
    
  tasks:
    - name: Pre-flight checks
      block:
        - name: Ensure required commands are available
          command: which {{ item }}
          with_items:
            - virsh
            - virt-install
            - qemu-img
            - cloud-localds
            - ssh-keygen
            - ssh
          register: cmd_check
          failed_when: cmd_check.rc != 0

        - name: Ensure SSH directory exists
          file:
            path: ~/.ssh
            state: directory
            mode: '0700'

        - name: Check libvirt is running
          systemd:
            name: libvirtd
            state: started
          become: yes

    - name: Phase 1 - Create VMs with reliable SSH
      include_tasks: tasks/create-vms-enhanced.yml

    - name: Phase 2 - Verify SSH connectivity
      include_tasks: tasks/verify-ssh.yml

    - name: Phase 3 - Generate Kubespray inventory
      include_tasks: tasks/generate-inventory.yml

    - name: Phase 4 - Deploy Kubernetes
      include_tasks: tasks/deploy-kubernetes.yml
      when: deploy_kubernetes | default(true) | bool