---
- name: "Complete K8s cluster deployment - VMs + Kubernetes"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    kvm_host: "192.168.1.99"
    kvm_user: "mike"
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"  # Changed from ssh_key to ssh_public_key
    cluster_vms:
      k8s-control:
        memory: 4096
        vcpus: 2
        disk: 30
        role: control
      k8s-worker1:
        memory: 4096
        vcpus: 2
        disk: 20
        role: worker
      k8s-worker2:
        memory: 4096
        vcpus: 2
        disk: 20
        role: worker
  
  tasks:
    - name: "Phase 1: Create VMs with reliable SSH"
      include_tasks: tasks/create-vms.yml
    
    - name: "Phase 2: Generate Kubespray inventory"
      include_tasks: tasks/generate-inventory.yml
    
    - name: "Phase 3: Test connectivity"
      include_tasks: tasks/test-connectivity.yml