---
# destroy-k8s-from-pi.yml - Run from Pi to destroy VMs on laptop

- name: Destroy K8s cluster on laptop from Raspberry Pi
  hosts: laptop
  gather_facts: no
  
  tasks:
    - name: Confirm destruction
      pause:
        prompt: "This will destroy ALL K8s VMs on {{ inventory_hostname }}. Type 'yes' to continue"
      register: confirm

    - name: Check confirmation
      fail:
        msg: "Destruction cancelled"
      when: confirm.user_input != "yes"

    - name: Destroy all VMs
      become: yes
      shell: |
        for vm in k8s-control k8s-worker1 k8s-worker2; do
          echo "Destroying $vm..."
          virsh destroy $vm 2>/dev/null || true
          virsh undefine $vm --remove-all-storage 2>/dev/null || true
        done
      ignore_errors: yes

    - name: Clean up disk images
      become: yes
      shell: |
        rm -f /var/lib/libvirt/images/k8s-*.qcow2
      ignore_errors: yes

    - name: Clean up cloud-init files
      shell: |
        rm -f /tmp/cloud-init-*.iso
        rm -f /tmp/cloud-init-*.yml
      ignore_errors: yes

    - name: Report status
      debug:
        msg:
          - "================================"
          - "All K8s VMs destroyed on laptop!"
          - "================================"