---
- name: "Get kubeconfig from Kubernetes cluster"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    kvm_host: "192.168.1.99"
    kvm_user: "mike"

  tasks:
    - name: "Get control plane IP"
      shell: |
        ssh {{ kvm_user }}@{{ kvm_host }} "
        sudo virsh domifaddr k8s-control | grep -E '192\.168\.' | awk '{print \$4}' | cut -d'/' -f1"
      register: control_ip_result

    - name: "Set control plane IP"
      set_fact:
        control_ip: "{{ control_ip_result.stdout.strip() }}"

    - name: "Verify control plane IP"
      fail:
        msg: "Could not get control plane IP. Check if k8s-control VM is running."
      when: control_ip == ""

    - name: "Display control plane IP"
      debug:
        msg: "Control plane IP: {{ control_ip }}"

    - name: "Create .kube directory"
      file:
        path: "~/.kube"
        state: directory
        mode: '0755'

    - name: "Copy kubeconfig from control plane"
      shell: |
        scp -o ProxyJump={{ kvm_user }}@{{ kvm_host }} -o StrictHostKeyChecking=no \
        ubuntu@{{ control_ip }}:/etc/kubernetes/admin.conf ~/.kube/config
      register: kubeconfig_copy

    - name: "Set kubeconfig permissions"
      file:
        path: "~/.kube/config"
        mode: '0600'

    - name: "Test kubectl connectivity"
      shell: kubectl get nodes
      register: kubectl_test
      ignore_errors: yes

    - name: "Display kubectl test results"
      debug:
        msg: "{{ kubectl_test.stdout_lines }}"
      when: kubectl_test.rc == 0

    - name: "Kubeconfig setup complete"
      debug:
        msg: |
          Kubeconfig copied successfully!
          
          Your cluster is accessible via kubectl:
          - kubectl get nodes
          - kubectl get pods --all-namespaces
          - kubectl cluster-info
          
          To test cluster functionality:
          ansible-playbook test-cluster.yml