- name: Deploy Kubernetes on VMs
  hosts: all
  become: yes
  tasks:
    - name: Install k3s on control node
      shell: |
        curl -sfL https://get.k3s.io | sh -
      when: inventory_hostname == "k8s-control"

    - name: Join worker nodes
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k8s-control']['ansible_host'] }}:6443 K3S_TOKEN=YOUR_TOKEN sh -
      when: inventory_hostname != "k8s-control"
