- name: Generate inventory file
  hosts: localhost
  tasks:
    - name: Create static inventory
      copy:
        dest: inventory.ini
        content: |
          [laptop]
          192.168.1.99 ansible_user=mike ansible_ssh_private_key_file=~/.ssh/id_ed25519
