---
# tasks/verify-ssh.yml
- name: Wait for SSH port to be open (10 minute timeout)
  wait_for:
    host: "{{ item.value }}"
    port: 22
    delay: 10
    timeout: 600  # 10 minutes
    state: started
  with_dict: "{{ vm_ip_addresses }}"

- name: Note about SSH testing from laptop
  debug:
    msg:
      - "NOTE: The VMs are configured with your Raspberry Pi's SSH key."
      - "SSH tests from this laptop will fail if it doesn't have the same key."
      - "This is expected! You'll SSH from your Raspberry Pi instead."

- name: Display connection info for Raspberry Pi
  debug:
    msg:
      - "Ready for Raspberry Pi connections!"
      - "From your Raspberry Pi, test with:"
      - "  ssh ansible@{{ vm_ip_addresses['k8s-control'] }}"
      - "  ssh ansible@{{ vm_ip_addresses['k8s-worker1'] }}"
      - "  ssh ansible@{{ vm_ip_addresses['k8s-worker2'] }}"

- name: Check if we can ping the VMs (network connectivity)
  shell: ping -c 2 -W 2 {{ item.value }}
  register: ping_test
  with_dict: "{{ vm_ip_addresses }}"
  ignore_errors: yes

- name: Display network connectivity status
  debug:
    msg: "{{ item.item.key }}: {{ 'Network REACHABLE' if item.rc == 0 else 'Network UNREACHABLE' }}"
  with_items: "{{ ping_test.results }}"

- name: Create SSH config for easier access from Raspberry Pi
  copy:
    dest: ~/ssh-config-for-pi.txt
    content: |
      # Add this to ~/.ssh/config on your Raspberry Pi for easier access:
      
      Host k8s-control
          HostName {{ vm_ip_addresses['k8s-control'] }}
          User ansible
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
      
      Host k8s-worker1
          HostName {{ vm_ip_addresses['k8s-worker1'] }}
          User ansible
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
      
      Host k8s-worker2
          HostName {{ vm_ip_addresses['k8s-worker2'] }}
          User ansible
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
      
      # Then you can simply use:
      # ssh k8s-control
      # ssh k8s-worker1
      # ssh k8s-worker2

- name: Display SSH config location
  debug:
    msg: 
      - "SSH config for your Raspberry Pi saved to: ~/ssh-config-for-pi.txt"
      - "Copy this to your Raspberry Pi's ~/.ssh/config for easier access"